version: '3'
services:
  scs-database:
    container_name: scs-db
    image: postgres:12
    restart: unless-stopped
      #user: "1000"
    volumes:
      - "/home/ramses/Documents/projects/volumes/database:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
      POSTGRES_DB: 'scs'
