version: '3'
services:
  database:
    container_name: scs-db
    image: postgres:12
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
      POSTGRES_DB: 'scs'