spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/scs
    username: admin
    password: pwd

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

# SERVER CONFIGS
server:
  port: 8082
